-- AlterTable
ALTER TABLE "sip_peers" ADD COLUMN     "accountcode" VARCHAR(40),
ADD COLUMN     "allowoverlap" VARCHAR(10),
ADD COLUMN     "allowsubscribe" VARCHAR(10),
ADD COLUMN     "amaflags" VARCHAR(40),
ADD COLUMN     "auth" VARCHAR(40),
ADD COLUMN     "autoframing" VARCHAR(10),
ADD COLUMN     "buggymwi" VARCHAR(10),
ADD COLUMN     "busylevel" INTEGER,
ADD COLUMN     "callcounter" VARCHAR(10),
ADD COLUMN     "callerid" VARCHAR(40),
ADD COLUMN     "callgroup" VARCHAR(40),
ADD COLUMN     "callingpres" VARCHAR(20),
ADD COLUMN     "cid_number" VARCHAR(40),
ADD COLUMN     "constantssrc" VARCHAR(10),
ADD COLUMN     "contactdeny" VARCHAR(95),
ADD COLUMN     "contactpermit" VARCHAR(95),
ADD COLUMN     "defaultip" VARCHAR(45),
ADD COLUMN     "defaultuser" VARCHAR(40),
ADD COLUMN     "deny" VARCHAR(95),
ADD COLUMN     "directmedia" VARCHAR(10) DEFAULT 'no',
ADD COLUMN     "faxdetect" VARCHAR(10),
ADD COLUMN     "fromdomain" VARCHAR(40),
ADD COLUMN     "fromuser" VARCHAR(40),
ADD COLUMN     "fullname" VARCHAR(40),
ADD COLUMN     "hasvoicemail" VARCHAR(10),
ADD COLUMN     "insecure" VARCHAR(40),
ADD COLUMN     "mailbox" VARCHAR(40),
ADD COLUMN     "maxcallbitrate" INTEGER,
ADD COLUMN     "md5secret" VARCHAR(40),
ADD COLUMN     "mohinterpret" VARCHAR(40),
ADD COLUMN     "mohsuggest" VARCHAR(40),
ADD COLUMN     "outboundproxy" VARCHAR(40),
ADD COLUMN     "parkinglot" VARCHAR(40),
ADD COLUMN     "permit" VARCHAR(95),
ADD COLUMN     "pickupgroup" VARCHAR(40),
ADD COLUMN     "progressinband" VARCHAR(10),
ADD COLUMN     "promiscredir" VARCHAR(10),
ADD COLUMN     "qualifyfreq" INTEGER,
ADD COLUMN     "regexten" VARCHAR(40),
ADD COLUMN     "regserver" VARCHAR(20),
ADD COLUMN     "remotesecret" VARCHAR(40),
ADD COLUMN     "rfc2833compensate" VARCHAR(10),
ADD COLUMN     "rtpholdtimeout" INTEGER,
ADD COLUMN     "rtpkeepalive" INTEGER,
ADD COLUMN     "rtptimeout" INTEGER,
ADD COLUMN     "sendrpid" VARCHAR(10),
ADD COLUMN     "session-expires" INTEGER,
ADD COLUMN     "session-minse" INTEGER,
ADD COLUMN     "session-refresher" VARCHAR(10),
ADD COLUMN     "session-timers" VARCHAR(10),
ADD COLUMN     "setvar" VARCHAR(200),
ADD COLUMN     "subscribecontext" VARCHAR(80),
ADD COLUMN     "subscribemwi" VARCHAR(10),
ADD COLUMN     "t38pt_usertpsource" VARCHAR(10),
ADD COLUMN     "textsupport" VARCHAR(10),
ADD COLUMN     "timerb" INTEGER,
ADD COLUMN     "timert1" INTEGER,
ADD COLUMN     "transport" VARCHAR(10),
ADD COLUMN     "trunkname" VARCHAR(40),
ADD COLUMN     "trustrpid" VARCHAR(10),
ADD COLUMN     "useclientcode" VARCHAR(10),
ADD COLUMN     "useragent" VARCHAR(40),
ADD COLUMN     "usereqphone" VARCHAR(10),
ADD COLUMN     "videosupport" VARCHAR(10),
ADD COLUMN     "vmexten" VARCHAR(40),
ALTER COLUMN "language" SET DATA TYPE VARCHAR(40),
ALTER COLUMN "disallow" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "allow" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "ipaddr" SET DATA TYPE VARCHAR(45);
