import { mkdir, rename, rm, writeFile } from 'fs/promises'
import { dirname } from 'path'
import { prisma } from '../lib/prisma'
import { logger } from '../utils/logger'
import { validateEnv } from '../config/env'
import { runAmiCommand } from './ami-client'

// Materializa o dialplan de contextos compartilhados de baixa escrita (holidays, timeconditions,
// announcements, ivrs, queues-app, request-templates) em arquivo estático por empresa, em vez de
// linhas na tabela `extensions` — pbx_realtime não tem cache, então cada Goto nesses contextos batia
// direto no Postgres a cada ligação. Como essas entidades só mudam via CRUD (nunca por chamada),
// materializar em arquivo elimina a query em tempo de chamada. `ramais`/`from-trunk-routed` continuam
// via Realtime (alta escrita, fora do escopo).
const env = validateEnv()
export const DIALPLAN_EXTRA_DIR = env.DIALPLAN_EXTRA_DIR

export type DialplanRow = { context: string; exten: string; priority: number; app: string; appdata: string | null }

export const dialplanFilePath = (context: string, asteriskId: string) => `${DIALPLAN_EXTRA_DIR}/${context}/${asteriskId}.conf`

export async function resolveAsteriskId(companyId: string): Promise<string> {
    const company = await prisma.company.findUniqueOrThrow({ where: { id: companyId }, select: { asteriskId: true } })
    return company.asteriskId
}

// Cada linha de prioridade 1 abre um novo `exten =>`; as seguintes usam `same => n` (Asterisk
// autoincrementa a prioridade) — equivalente ao par (app,appdata) que ia pra cada coluna da tabela
// `extensions`. appdata já vem pronto como argumento único da app (pode conter vírgulas — a app é
// quem parseia o próprio appdata, igual acontecia lendo a coluna via Realtime).
// Asterisk lê o .conf linha a linha — um \r ou \n dentro de exten/app/appdata quebraria pra uma nova
// diretiva de dialplan (ex: nome de IVR/TimeCondition/Holiday com newline injetaria System()/AGI =
// RCE no host). Remove caracteres de controle aqui como defesa central, independente da origem do valor.
const stripControl = (s: string) => s.replace(/[\x00-\x1f\x7f]/g, '')

function renderEntries(entries: DialplanRow[]): string {
    const lines: string[] = []
    let currentExten: string | null = null
    for (const e of entries) {
        const exten = stripControl(e.exten)
        const app = stripControl(e.app)
        const appdata = stripControl(e.appdata ?? '')
        if (exten !== currentExten) {
            lines.push(`exten => ${exten},1,${app}(${appdata})`)
            currentExten = exten
        } else {
            lines.push(` same => n,${app}(${appdata})`)
        }
    }
    return lines.length > 0 ? lines.join('\n') + '\n' : ''
}

// English on purpose — this header ends up inside the generated .conf file itself, read by
// whoever opens it on the Asterisk box, not just by devs reading this repo's Portuguese comments.
const generatedFileHeader = (context: string, asteriskId: string) => `; AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
; Generated by Sofon PABX (src/asterisk/dialplan-file.repository.ts) at ${new Date().toISOString()}
; Context: ${context} | Company (asteriskId): ${asteriskId}
; Regenerated from scratch and OVERWRITTEN on every create/update/delete for this company/context.
; Any manual change here will be lost on the next write.
`

// rename() é atômico no mesmo filesystem — evita o `dialplan reload` ler o arquivo pela metade
// enquanto ele está sendo escrito.
export async function writeContextFile(context: string, asteriskId: string, entries: DialplanRow[]) {
    const path = dialplanFilePath(context, asteriskId)
    if (entries.length === 0) {
        await rm(path, { force: true })
        return
    }
    await mkdir(dirname(path), { recursive: true })
    const tmpPath = `${path}.tmp-${process.pid}-${Date.now()}`
    await writeFile(tmpPath, generatedFileHeader(context, asteriskId) + renderEntries(entries), 'utf8')
    await rename(tmpPath, path)
}

// Via AMI (src/asterisk/ami-client.ts) em vez de spawnar o binário `asterisk` — dispensa ter o CLI
// do Asterisk instalado no mesmo host/container do backend. Falha aqui não derruba a request: o
// arquivo já está correto, o próximo reload (manual ou próximo CRUD) resolve.
//
// Chamadores NÃO devem dar await nisso — o arquivo já está correto no disco quando a request
// responde; o reload só precisa acontecer em algum momento depois, sem segurar a request pra isso.
const RELOAD_DEBOUNCE_MS = 500
let pendingReload: Promise<void> | null = null

// Debounce: CRUDs concorrentes de empresas/contextos diferentes (cada um já escreveu seu próprio
// arquivo antes de chamar isso) caem no mesmo reload em vez de um `dialplan reload` global por write —
// sem isso, 20 empresas editando quase junto disparam 20 reloads globais quase simultâneos.
export function reloadDialplan(): Promise<void> {
    if (pendingReload) return pendingReload
    pendingReload = new Promise((resolve) => {
        setTimeout(async () => {
            try {
                await runAmiCommand('dialplan reload')
            } catch (error) {
                logger.warn({ event: 'dialplan.reload.failed', error: error instanceof Error ? error.message : String(error) })
            } finally {
                pendingReload = null
                resolve()
            }
        }, RELOAD_DEBOUNCE_MS)
    })
    return pendingReload
}

// Best-effort: remove os arquivos das empresa em todos os contextos migrados — usado no delete de
// Company, quando não há mais nada pra "regenerar" (a empresa já não existe).
export async function removeCompanyDialplanFiles(asteriskId: string, contexts: string[]) {
    await Promise.all(contexts.map((context) => rm(dialplanFilePath(context, asteriskId), { force: true })))
    reloadDialplan()
}

// Serializa regenerações concorrentes da mesma empresa+contexto (ex: dois CRUDs quase simultâneos)
// pra evitar duas escritas de tmp-file/replace intercaladas na mesma chave.
const locks = new Map<string, Promise<unknown>>()

export function withDialplanLock<T>(key: string, fn: () => Promise<T>): Promise<T> {
    const previous = locks.get(key) ?? Promise.resolve()
    const run = previous.then(fn, fn)
    locks.set(key, run.then(() => undefined, () => undefined))
    return run
}
