import { mkdir, rename, rm, symlink, writeFile } from 'fs/promises'
import { dirname } from 'path'
import { prisma } from '../../lib/prisma'
import { validateEnv } from '../../config/env'
import { logger } from '../../utils/logger'
import { runAmiCommand } from '../transport/ami-client'
import { resolveAsteriskId, withDialplanLock } from '../dialplan/dialplan-file.repository'
import { audioSoundDir, audioSoundPath } from './audio.repository'

// Música de espera (MOH) por fila: cada Audio usado como MOH vira uma classe `moh-<audioId>`
// (audioId é cuid2, seguro como nome de seção .conf), com diretório próprio contendo um symlink
// pro .wav já convertido - Asterisk `mode=files` toca TODO arquivo do diretório, por isso a
// classe não pode compartilhar pasta com o restante dos sons da empresa. Classe é keyed por
// audioId (não por queueId) pra várias filas usando o mesmo áudio compartilharem a mesma classe.
// Mesmo padrão de dialplan-file.repository.ts: escrita atômica (tmp+rename), arquivo por empresa
// incluído via #tryinclude, reload debounced via AMI Command.
const env = validateEnv()
export const MUSICONHOLD_EXTRA_DIR = `${env.ASTERISK_CONF_DIR}/musiconhold-extra`

export const mohClassName = (audioId: string) => `moh-${audioId}`
export const mohDir = (asteriskId: string, audioId: string) => `${audioSoundDir(asteriskId)}/moh/${audioId}`
export const musiconholdFilePath = (asteriskId: string) => `${MUSICONHOLD_EXTRA_DIR}/${asteriskId}.conf`

type MohEntry = { class: string; directory: string }

function renderMohEntries(entries: MohEntry[]): string {
    return entries.map((e) => `[${e.class}]\nmode=files\ndirectory=${e.directory}\n`).join('\n')
}

// English on purpose - this header ends up inside the generated .conf file itself, read by
// whoever opens it on the Asterisk box, not just by devs reading this repo's Portuguese comments.
const generatedFileHeader = (asteriskId: string) => `; AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
; Generated by Sofon PABX (src/asterisk/destinations/musiconhold.repository.ts) at ${new Date().toISOString()}
; Company (asteriskId): ${asteriskId}
; Regenerated from scratch and OVERWRITTEN on every Queue create/update/delete or Audio delete
; that touches a mohAudioId for this company. Any manual change here will be lost on the next write.
`

// rename() é atômico no mesmo filesystem - evita o reload ler o arquivo pela metade enquanto ele
// está sendo escrito (mesmo padrão de writeContextFile em dialplan-file.repository.ts).
async function writeMusiconholdExtraFile(asteriskId: string, entries: MohEntry[]) {
    const path = musiconholdFilePath(asteriskId)
    if (entries.length === 0) {
        await rm(path, { force: true })
        return
    }
    await mkdir(dirname(path), { recursive: true })
    const tmpPath = `${path}.tmp-${process.pid}-${Date.now()}`
    await writeFile(tmpPath, generatedFileHeader(asteriskId) + renderMohEntries(entries), 'utf8')
    await rename(tmpPath, path)
}

// Idempotente: symlink já existente (EEXIST) não é erro - só falha se o alvo do Audio ainda não
// foi convertido/gravado (persistAudioFile roda antes de qualquer Queue poder referenciar o audioId,
// via assertAudioBelongsToCompany, então isso não deveria acontecer em uso normal).
async function ensureMohSymlink(asteriskId: string, audioId: string) {
    const dir = mohDir(asteriskId, audioId)
    await mkdir(dir, { recursive: true })
    const linkPath = `${dir}/${audioId}.wav`
    const target = `${audioSoundPath(asteriskId, audioId)}.wav`
    await symlink(target, linkPath).catch((error) => {
        if ((error as NodeJS.ErrnoException).code !== 'EEXIST') throw error
    })
}

// Best-effort: remove o diretório/symlink da classe - usado quando o Audio referenciado é
// deletado (audios.service.ts) ou deixa de ser usado como MOH por qualquer fila.
export async function removeMohClassDir(asteriskId: string, audioId: string) {
    await rm(mohDir(asteriskId, audioId), { recursive: true, force: true })
}

// Via AMI (mesmo cliente de dialplan-file.repository.ts) em vez de spawnar o binário `asterisk`.
// Chamadores NÃO devem dar await nisso - o arquivo já está correto no disco quando a request
// responde; o reload só precisa acontecer em algum momento depois, sem segurar a request pra isso.
const RELOAD_DEBOUNCE_MS = 500
let pendingReload: Promise<void> | null = null

export function reloadMusiconhold(): Promise<void> {
    if (pendingReload) return pendingReload
    pendingReload = new Promise((resolve) => {
        setTimeout(async () => {
            try {
                await runAmiCommand('module reload res_musiconhold.so')
            } catch (error) {
                logger.warn({ event: 'musiconhold.reload.failed', error: error instanceof Error ? error.message : String(error) })
            } finally {
                pendingReload = null
                resolve()
            }
        }, RELOAD_DEBOUNCE_MS)
    })
    return pendingReload
}

export const MusicOnHoldRepository = {
    // Reconstrói o arquivo de classes MOH da empresa inteira, a partir do estado atual em banco -
    // chamado depois de qualquer create/update de Queue que mude mohAudioId, e depois de deletar
    // um Audio referenciado por alguma fila como MOH.
    async regenerate(companyId: string) {
        const asteriskId = await resolveAsteriskId(companyId)
        return withDialplanLock(`musiconhold:${asteriskId}`, async () => {
            const rows = await prisma.queue.findMany({
                where: { companyId, mohAudioId: { not: null } },
                select: { mohAudioId: true },
            })
            const audioIds = [...new Set(rows.map((r) => r.mohAudioId!))]
            for (const audioId of audioIds) await ensureMohSymlink(asteriskId, audioId)
            const entries = audioIds.map((audioId) => ({ class: mohClassName(audioId), directory: mohDir(asteriskId, audioId) }))
            await writeMusiconholdExtraFile(asteriskId, entries)
            reloadMusiconhold()
        })
    },
}
